require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
Layout/LineLength:
  Exclude:
    - "db/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Style/Documentation:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - "config/**/*"
    - "db/**/*"
Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"
Metrics/MethodLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"
