require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
Layout/LineLength:
  Exclude:
    - "db/**/*"
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
Metrics/AbcSize:
  Exclude:
    - "config/**/*"
    - "db/**/*"
Metrics/BlockLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"
Metrics/MethodLength:
  Exclude:
    - "config/**/*"
    - "db/**/*"
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleExpectations:
  Enabled: false
